DROP TABLE IF EXISTS pizzas;

CREATE TABLE pizzas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    toppings TEXT NOT NULL,
    rating INTEGER NOT NULL
)

DROP TABLE IF EXISTS rats;

CREATE TABLE rats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    size TEXT NOT NULL,
    location TEXT NOT NULL,
    likes_pizza BOOLEAN NOT NULL
)

