DROP TABLE IF EXISTS pizzas;
DROP TABLE IF EXISTS rats;

CREATE TABLE pizzas (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    toppings TEXT NOT NULL,
    rating INTEGER NOT NULL
);

CREATE TABLE rats (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    size TEXT NOT NULL,
    location TEXT NOT NULL,
    likes_pizza BOOL NOT NULL
);

